[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/stashes"
  to = "/.netlify/functions/get_stashes"
  status = 200

[[redirects]]
  from = "/api/submit-stash"
  to = "/.netlify/functions/submit-stash"
  status = 200

[[redirects]]
  from = "/api/admin-get"
  to = "/.netlify/functions/admin-get"
  status = 200

# Eski admin-update'i silebilirsin, yerine admin-edit geldi
[[redirects]]
  from = "/api/admin-edit"
  to = "/.netlify/functions/admin-edit"
  status = 200

[[redirects]]
  from = "/api/admin-add-official"
  to = "/.netlify/functions/admin-add-official"
  status = 200
